spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.91.131:3306/gulimall_pms?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.91.131:8848
  application:
    name: gulimall-product
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
#配置MP邏輯刪除
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
logging:
  level:
    com.atguigu.gulimall: debug