spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.91.131:3306/gulimall_oms?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF8
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: gulimall-order
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto